### ISSUE TITLE
[1장] 사용자 수에 따른 규모 확장성

### ISSUE THREAD

**Issue by SmileJune** [aronalee/swm_backend_study#2]

**Comment by aronalee** [comment]
# 요약

## scale-out과 scale-up

- scale-up의 한계: 현시점 낼 수 있는 자원의 최대양 이상으로 넘을 수 없다.
- scale-out의 한계: failover, re-dundancy에 대한 개발자의 고민이 필요함

## LB의 역할

- 가용성: 서버 하나가 죽어도 다른 서버로 포워딩
- 트래픽 분산: 같은 기능을 처리하는 서버들에게 처리해야하는 트래픽을 분산

## DB 다중화

- master: 쓰기 연산만 진행하는 rdbms
- slave: 읽기 연산만 지원하는 rdbms
- master-slave의 특징
   1. 병렬로 읽기 처리가 가능
   2. DR이 가능 => master가 죽으면 slave중 하나가 master로 승격
   3. 일부 데이터 손실이 발생 할 수 있음

## cache 관리 전략

- 데이터 삭제 정책: 캐시를 얼마동안 가지고 있다가 지울 것인가,
- 데이터 방출 정책: 캐시가 차있는 경우 새로운 데이터가 들어오면 어느 데이터를 지울 것이냐
- 메모리 정책: 캐시 메모리는 얼마나 잡을 것인가
- 일관성 준수: 실제 정보와 캐시 정보의 데이터 정합성은 어떻게 맞출 것이냐
- 장애 대응: 캐시서버에 장애가 발생할 경우의 대응책은 무엇인가

## CDN

- CDN은 서버와 클라이언트간의 물리적 거리가 길 때 중간에 캐싱을 하는 기술
- CDN의 고려사항
   1. CDN은 비싸다
   2. CDN의 캐시 만료 및 갱신 정책
   3. CDN의 장애 대응 정책

---

# 생각

읽어보니 AWS의 관리형 서비스들과 비슷하다고 생각이 들었다. AWS RDS정책의 경우 Master-Slave로 만들 수 있으며 Master가 죽으면 Slave가 Master로 승격할 수 있는 규칙이 있다.
또한 캐시 정책은 생각을 안해봤었는데  이 원칙들을 읽어보니 서비스를 만들 때 고려해야한다는 생각을 하였다.

**Comment by SmileJune** [comment]
### 단일 서버

웹 앱, DB, 캐시 등이 모두 서버 한 대에서 실행되는 구조

### 데이터베이스

사용자가 늘면 서버 하나로는 충분하지 않아서 여러 서버를 두어야 한다.

1. 웹/모바일 트래픽 처리 용도(웹 계층)
2. 데이터베이스 서버(데이터 계층)

DB 선택 기준

대부분은 관계형 데이터베이스가 최선이지만 특정한 경우에는 비-관계형 데이터베이스를 사용한다.

1. 아주 낮은 응답 지연시간(latency)이 요구될 때
2. 다루는 데이터가 비정형이라 관계형 데이터가 아닐 때
3. 데이터를 직렬화하거나 역직렬화 할 수 있기만 하면 될 때
4. 아주 많은 양의 데이터를 저장할 필요가 있을 때

### 수직적 규모 확장 vs 수평적 규모 확장

스케일 업 : 고사양 자원을 추가하는 행위(수직적 규모 확장)

스케일 아웃 : 더 많은 서버를 추가해 성능을 개선하는 행위(수평적 규모 확장)

수직적 규모 확장에는 한계가 있고, 장애에 대한 failover 방안이나 다중와 방안을 제시할 수 없다.

따라서 대규모 애플리케이션을 지원하는 데는 수평적 규모 확장법이 적절하다.

**로드밸런서**

부하 분산 집합(load balancing set)에 속한 웹 서버들에게 트래픽 부하를 고르게 분산하는 역할

로드밸런서를 이용해 서버를 이중화 했지만 여전히 데이터 계층은 불안하다.

**데이터베이스 다중화**

쓰기 연산은 마스터에서만 지원

읽기 연산은 마스터, 슬레이브 둘 다 지원

대부분의 애플리케이션은 읽기 연산의 비중이 쓰기 연산보다 훨씬 높기 때문에 많은 부 데이터베이스 서버를 갖는다.

만약 주 데이터베이스에 문제가 생겼다면 부 데이터베이스 하나를 주 데이터베이스로 지정하고 장애를 극복한다.

부 데이터베이스가 최신 상태가 아니라면 복구 스크립트를 돌려서 추가해야 한다.

### 캐시

값비싼 연산 결과 또는 자주 참조되는 데이터를 메모리 안에 두고, 뒤이은 요청이 보다 빨리 처리될 수 있도록 하는 저장소

**캐시 계층**

데이터가 잠시 보관되는 곳으로 데이터베이스보다 훨씬 빠르다.

성능 개선 및 데이터베이스의 부하를 줄일 수 있다.

******************************************************캐시 사용 시 유의할 점******************************************************

- 데이터 갱신은 자주 일어나지 않지만 참조가 빈번할 때 사용
- 중요 데이터는 여전히 지속적 저장소에 두자
- 만료 기간을 적절한 기간으로 설정해놓자
- 캐시 서버를 한 대만 두는 경우 해당 서버가 단일 장애 지점(Single Point of Failure, SPOF)이 될 수 있다. → 여러 지역에 걸쳐 캐시 서버를 분산시켜야 한다.
- 캐시 메모리가 작으면 데이터가 자주 캐시에서 밀려나(eviction) 캐시 성능이 저하된다. → 캐시 메모리를 과할당(overprovision) 시켜 캐시에 보관될 데이터가 갑자기 늘어났을 때 문제를 방지한다.
- 데이터 방출 정책(eviction)은 캐시가 꽉 찼을 때, 기존 데이터를 내보내는 것이다. 가장 많이 사용하는 것은 LRU(Least Recently Used). LFU(Least Frequency Used)와 FIFO 정책도 있다.

### 콘텐츠 전송 네트워크(CDN)

정적 콘텐츠를 전송하는 데 쓰이는, 지리적으로 분산된 서버의 네트워크

이미지, 비디오, CSS, JS파일 등을 캐시할 수 있다.

**CDN 사용 시 고려해야 할 사항**

- 비용
- 만료 시한 설정
- CDN 장애에 대한 대처 방안
- 콘텐츠 무효화(invalidation) 방법
    - CDN 서비스 사업자가 제공하는 API 이용
    - 콘텐츠의 다른 버전을 서비스하도록 오브젝트 버저닝 이용

### 무상태(stateless) 웹 계층

웹 계층을 수평적으로 확장하는 방법을 고민해보자.

상태 정보(사용자 세션 데이터 같은)를 웹 계층에서 제거해야 한다. → 상태 정보를 저장소에 보관하고 필요할 때 가져온다.

**************************************상태 정보 의존적인 아키텍처**************************************

같은 클라이언트의 요청은 항상 같은 서버로 전송되어야 한다.

대부분 로드밸런서가 sticky session 기능을 제공하고 있는데, 이는 로드밸런서에 부담을 준다.

**********************************무상태 아키텍처**********************************

상태 정보가 필요할 경우 공유 저장소로부터 데이터를 가져온다.

### 데이터 센터

장애가 없는 상황에서 가장 가까운 데이터 센터로 안내되는데, 이 절차를 지리적 라우팅(geoDNS-routing 또는 geo-routing)이라고 부른다.

다중 데이터센터 아키텍처를 만들려면 몇 가지 기술적 난제를 해결해야 한다.

- 트래픽 우회
- 데이터 동기화
- 테스트와 배포

### 메시지 큐

메시지 큐는 메시지의 무손실을 보장하는, 비동기 통신을 지원한다.

### 로그, 메트릭 그리고 자동화

- 로그 : 에러 로그를 모니터링하는 것은 중요하다.
- 메트릭 : 메트릭을 잘 수집하면 사업에 대한 유용한 정보를 얻거나 시스템의 상태를 빠르게 파악할 수 있다.
    - 호스트 단위 메트릭 : CPU, 메모리, 디스크 I/O
    - 종합(aggregated) 메트릭: 데이터베이스 계층의 성능, 캐시 계층의 성능
    - 핵심 비즈니스 메트릭: 일별 능동 사용자, 수익, 재방문
- 자동화 : CI, 빌드, 테스트, 배포 등의 절차를 자동화할 수 있다.

### 데이터베이스의 규모 확장

저장할 데이터가 많아지면 데이터베이스에 대한 부하도 증가한다.

데이터베이스의 규모 확장법

1. 수직적 확장
2. 수평적 확장 : 샤딩(sharding)이라고도 부르는데, 더 많은 서버를 추가함으로써 성능을 향상시킨다.

### 백만 사용자, 그리고 그 이상

시스템을 최적화하고 더 작은 단위의 서비스로 분할해야 한다.
