### ISSUE TITLE
[2장] 개략적인 규모 추정

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_backend_study#3]

**Comment by aronalee** [comment]
# 요약

- 정확한 수치가 아닌 개략적인 수치로 접근해야 한다( 1mb=1024kb=1000kb)
- 구글에서 통상적인 컴퓨터의 연산에 대한 응답 지연 값에 의하며 물리적인 거리가 가장 클 때 지연시간이 가장 높았다.
- 메모리는 빠르지만 HW는 느리다
- 단순 압축 알고리즘은 빠르다
- 가용성은 100%로 표시되지 않는다.
   - 99에서 뒤에 .9를 얼마나 붙냐에 따라 가용성에 차이가 있다.
   - 99%: 연간 3.65일 장애가 발생할 수 있음
   - 99.9: 연간 8.77시간동안 장애가 발생할 수 있음
- QPS: 초당 응답 가능한 쿼리양

---

# 생각

가용성에서 99.9%를 보장한다는 홍보를 보면 '이게 얼마정도의 장애를 발생하지' 라고 고민한 적이 있다. 책에서 표로 내용을 확인하니 궁금한 것이 해소가 되었다.

**Comment by SmileJune** [comment]
<p>개략적 규모 추정을 효과적으로 해 내려면 규모 확장성을 표현하는 데 필요한 기본기에 능숙해야 한다. 특히 2의 제곱수나 응답지연 값, 그리고 가용성에 관계된 수치들을 기본적으로 잘 이해하고 있어야 한다.</p>
<h3>2의 제곱수</h3>


2의 x제곱 | 근사치 | 축약형
-- | -- | --
10 | 1천 | 1KB
20 | 1백만 | 1MB
30 | 10억 | 1GB
40 | 1조 | 1TB
50 | 1000조 | 1PB


<h3>모든 프로그래머가 알아야 하는 응답지연 값</h3>
<img width="380" alt="스크린샷 2023-09-18 오후 8 55 45" src="https://github.com/aronalee/swm_backend_study/assets/91049936/185f1348-35e2-48c8-a6f3-281e6737cbf5">
<ul>
<li>메모리는 빠르지만 디스크는 아직도 느리다.</li>
<li>디스크 탐색은 가능한 한 피하라.</li>
<li>단순한 압축 알고리즘은 빠르다.</li>
<li>데이터를 인터넷으로 전송하기 전에 가능하면 압축하라.</li>
<li>데이터 센터는 보통 여러 지역에 분산되어 있고, 센터들 간에 데이터를 주고받는 데는 시간이 걸린다.</li>
</ul>
<h3>가용성에 관계된 수치들</h3>
<img width="376" alt="스크린샷 2023-09-18 오후 8 56 24" src="https://github.com/aronalee/swm_backend_study/assets/91049936/b69af31d-ef34-43ec-a7e9-0ac93f267f59">
<h3>계산 팁</h3>
<ul>
<li>근사치를 활용하라</li>
<li>가정들은 적어 둬라</li>

<li>단위를 붙여라</li>
<li>QPS, 최대 OPS, 저장소 요구량, 캐시 요구량, 서버 수를 추정하는 문제가 많이 나온다.</li>
</ul>
<p>연습 많이 해라!</p>
