### ISSUE TITLE
[3장] 시스템 설계 면접 공략

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_backend_study#4]

**Comment by aronalee** [comment]
# 요약

- 면접관을 동료라고 생각하고 질답을 통해 요구사항과 가정을 분명히 해라
- 설계시 고려요소
   - 만들어야하는 기능이 무엇인가
   - DAU, MAU등 제품의 능동 사용자수는 얼마인가
   - 회사의 규모는 얼마나 커지는가
   - 기술 스택은 어떤 것들을 쓰는가
- 설계 후
   - 만든 설계의 병목 구간이 무엇이며 어떻게 해결할 수 있는가
   - 비기능적 요구사항의 해결 방안
   - 서비스를 어떻게 운영할 것인가

---

# 생각

k8s를 사용하는 경우가 2가지라고 알고있었다. 첫번째는 수만개의 container를 이용해야하는 경우, 두번째가 성장가능성이라는 이야기를 들었다. 이 장을 읽어보니 두번째의 이유가 이해가 되었다. 성장이 빠르다면 container를 급격하게 늘려야 하므로 이를 받아드릴 수 있는 k8s가 적격일 수 있겠다는 생각을 하게 되었기 때문이다.

**Comment by SmileJune** [comment]
### 효과적인 면접을 위한 4단계 접근법

1. 문제 이해 및 설계 범위 확정
2. 개략적인 설계안 제시 및 동의 구하기
3. 상세 설계
4. 마무리

**시간배분**

1. 문제 이해 및 설계 범위 확정 : 3분에서 10분
2. 개략적 설계안 제시 및 동의 구하기 : 10분에서 15분
3. 상세 설계 : 10분에서 25분
4. 마무리 : 3분에서 5분
